mkdir "Communication Server"
mkdir "Computational Node"
mkdir "Task Manager"
mkdir "Client"
mkdir "Plugins"
mkdir "Communication Server\plugins"
mkdir "Computational Node\plugins"
mkdir "Task Manager\plugins"

del /Q "Communication Server\*.*"
del /Q "Computational Node\*.*"
del /Q "Task Manager\*.*"
del /Q "Client\*.*"
del /Q "Plugins\*.*"
del /Q "Communication Server\plugins\*.*"
del /Q "Computational Node\plugins\*.*"
del /Q "Task Manager\plugins\*.*"

copy "..\Source\ComputationalCluster.CommunicationServer.Runner\bin\Release\*.*" "Communication Server\*.*"
copy "..\Source\ComputationalCluster.ComputationalNode.Console\bin\Release\*.*" "Computational Node\*.*"
copy "..\Source\ComputationalCluster.TaskManager.Console\bin\Release\*.*" "Task Manager\*.*"
copy "..\Source\ComputationalCluster.ComputationalClient\bin\Release\*.*" "Client\*.*"

copy "..\Source\ComputationalCluster.TaskSolver.ArithmeticProgressionSum\bin\Release\ComputationalCluster.TaskSolver.ArithmeticProgressionSum.dll" "Plugins\"
copy "..\Source\ComputationalCluster.TaskSolver.DVRP\bin\Release\ComputationalCluster.TaskSolver.DVRP.dll" "Plugins\"
copy "Plugins\*.*" "Communication Server\plugins\*.*"
copy "Plugins\*.*" "Computational Node\plugins\*.*"
copy "Plugins\*.*" "Task Manager\plugins\*.*"
